### ISSUE TITLE
Blows up when receiving a request that doesn't have a "Host" header

### ISSUE THREAD

**Issue by jbrains** [mattt/rack-subdomain#8]
I tried to deploy a "scalable app" on OpenShift. I discovered that OpenShift's app monitors ping the app by sending it an HTTP/1.0 request that doesn't include the Host header (HTTP_HOST). This exposes a usually-but-not-always-valid assumption in rack-subdomain that HTTP_HOST is present in the request. I got a nil reference as the symptom, and feel lucky that it only took a couple of weeks to understand the problem. (I don't have the HTTP specification memorised.)

I have a terrible patch that seems to work at least to some degree on one machine so far. I'm so open to suggestions for improvement. I haven't thought deeply about the implications of the patch yet, because I want to get my app off Heroku onto OpenShift NOW.

**Comment by jbrains** [comment]
This relates to the problem: http://stackoverflow.com/questions/22319538/undefined-index-serverhttp-host-openshift-scalable-app

**Comment by mattt** [comment]
@jbrains Apologies for taking so long to respond to this. I'm sure your situation has changed since you originally posted this, but I wanted to let you know that 450edde should fix the bug you described. If not, please let me know. Thanks!

**Comment by jbrains** [comment]
I won't be able to confirm this for you, but I appreciate it all the same.
